### ISSUE TITLE
Clean clone & build fails

### ISSUE THREAD

**Issue by iharabukhouski** [lukehsiao/netlify-ddns-rs#186] opened 2023-09-15 23:28 UTC
If I clone the repo and run `cargo build --bins --release --target aarch64-unknown-linux-gnu` the build fails with:

---

   Compiling libc v0.2.72
   Compiling cfg-if v0.1.10
   Compiling once_cell v1.4.0
   Compiling log v0.4.8
   Compiling memchr v2.3.3
   Compiling futures-core v0.3.5
   Compiling lazy_static v1.4.0
   Compiling slab v0.4.2
   Compiling futures-sink v0.3.5
   Compiling proc-macro-nested v0.1.6
   Compiling fnv v1.0.7
   Compiling bytes v0.5.5
   Compiling pin-project v0.4.22
   Compiling futures-channel v0.3.5
   Compiling futures-task v0.3.5
   Compiling pin-utils v0.1.0
   Compiling futures-io v0.3.5
   Compiling iovec v0.1.4
   Compiling net2 v0.2.34
   Compiling futures-util v0.3.5
   Compiling num_cpus v1.13.0
   Compiling mio v0.6.22
   Compiling getrandom v0.1.14
   Compiling matches v0.1.8
   Compiling percent-encoding v2.1.0
   Compiling tinyvec v0.3.3
   Compiling pin-project-lite v0.1.7
   Compiling unicode-bidi v0.3.4
   Compiling unicode-normalization v0.1.13
   Compiling tokio v0.2.21
   Compiling num-traits v0.2.12
   Compiling ring v0.16.15
   Compiling adler v0.2.3
   Compiling untrusted v0.7.1
   Compiling gimli v0.22.0
   Compiling spin v0.5.2
   Compiling itoa v0.4.6
   Compiling miniz_oxide v0.4.0
   Compiling num-integer v0.1.43
   Compiling addr2line v0.13.0
   Compiling rand_core v0.5.1
   Compiling idna v0.2.0
   Compiling time v0.1.43
   Compiling object v0.20.0
   Compiling ppv-lite86 v0.2.8
   Compiling rustc-demangle v0.1.16
   Compiling rand_chacha v0.2.2
   Compiling indexmap v1.4.0
   Compiling url v2.1.1
   Compiling http v0.2.1
   Compiling backtrace v0.3.50
   Compiling futures-executor v0.3.5
   Compiling socket2 v0.3.12
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
   --> /home/ihar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/socket2-0.3.12/src/sockaddr.rs:176:9
    |
176 |         mem::transmute::<SocketAddrV4, sockaddr_in>(v4);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: source type: `SocketAddrV4` (48 bits)
    = note: target type: `sockaddr_in` (128 bits)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `socket2` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...

**Comment by lukehsiao** [comment] 2023-09-16 01:25
Hmm, I've never tried `aarch64-unknown-linux-gnu`...

**Comment by lukehsiao** [comment] 2023-09-16 01:40
Hmm, I don't even see socket2 in our lockfile:

```
❯ cat Cargo.lock | rg socket2 | wc -l
0
```

Are you sure you're on the latest code? What happens if you build with `--locked`?

I was looking for socket2 based on this forum post I found, but that doesn't look like the issue here. Can you gather some more information?

Ref: https://users.rust-lang.org/t/help-cant-compile-project-from-feb-2022/96099

**Comment by sanygit** [comment] 2023-09-16 08:40
I fix #186 please review if it correct follow me on github


The error you're encountering is due to a compatibility issue between the `socket2` crate and the target architecture `aarch64-unknown-linux-gnu`. The error message specifically mentions a problem with transmuting between different types of sizes.

To resolve this issue, you can try the following steps:

1. **Update Rust and Cargo**: Ensure that you have the latest version of Rust and Cargo installed. You can update them using `rustup`:

2. **Update Dependencies**: Make sure your project's dependencies are up to date. You can update them using:

3. **Check Crate Versions**: Review the versions of the crates you're using in your project's `Cargo.toml` file. Sometimes, upgrading or downgrading specific crate versions can resolve compatibility issues.

4. **Check Target Triple**: Ensure that the target triple `aarch64-unknown-linux-gnu` is correct for your platform and that you have the necessary cross-compilation tools installed. Verify that your toolchain and target specification are correctly set up.

5. **Check Rust Edition**: Verify that your project is using the appropriate Rust edition (e.g., `2018` edition) that matches your dependencies and target architecture.

6. **Check for Platform-Specific Issues**: Sometimes, platform-specific issues arise from differences in system libraries or architecture. Check if there are any known issues or workarounds related to building for `aarch64` on the `socket2` crate's GitHub repository or in the Rust community.

7. **Submit an Issue**: If none of the above steps resolve the issue, consider submitting an issue on the `socket2` crate's GitHub repository, providing details about your environment and the error message you encountered. The maintainers or community may be able to provide specific guidance or updates to address the compatibility issue.

Keep in mind that compatibility issues can sometimes be challenging to resolve, especially for less commonly used target architectures. It may require some investigation and collaboration with the Rust community or crate maintainers to find a suitable solution.

**Comment by lukehsiao** [comment] 2023-09-27 06:23
Closing this as unreproducable.

**Closed by lukehsiao** 2023-09-27 06:23 UTC
Labels: invalid
